### ISSUE TITLE
get不是函数

### ISSUE THREAD

**Issue by qq578023708** [tiandaox/egg-mssql#1]
`const mssql=require('mssql');
const Service = require('egg').Service;

class UserService extends Service{
    async find(){
        console.dir(this.app.mssql.get());
        return '123';
    }
}`

TypeError in /
this.app.mssql.get is not a function

**Comment by tiandaox** [comment]
单数据源使用标准的egg-mysql方式就可以了。
console.dir(await this.app.mssql);

**Comment by jackhenhao** [comment]
> `const mssql=require('mssql');
> const Service = require('egg').Service;
> 
> class UserService extends Service{
> async find(){
> console.dir(this.app.mssql.get());
> return '123';
> }
> }`
> 
> TypeError in /
> this.app.mssql.get is not a function

单数据源使用标准的egg-mysql方式就可以了。
console.dir(await this.app.mssql);

**Comment by qq578023708** [comment]
意思就是单数据源就不需要 get 指定的数据库配置了是吗?
:+1:    感谢您的指点!

**Comment by qq578023708** [comment]
Very Thinks!
